# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
# repositories:
#   stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    createuser/files: '../../../../files'
    createuser/manifests: '../../../../manifests'
    createuser/templates: '../../../../templates'
