name    'createuser'
version '1.0.0'
author 'puppet@example.com'
license 'All Rights Reserved'
summary 'UNKNOWN'
description 'UNKNOWN'
source 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'puppetlabs/stdlib', '>= 4.4.0'
